### ISSUE TITLE
Please check this error

### ISSUE THREAD

**Issue by shahriarshafin** [theenigma017/captive-portal-phishing-google#1]
Arduino: 1.8.13 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\shafi\Desktop\captive-portal-phishing-master\esportal\ESPortal.ino: In function 'void handle_portal()':

ESPortal:49:126: error: expected ')' before 'https'

   webServer.send(200, "text/html", "<html><body>Code authors :<br><br>Corey Harding(www.LegacySecurityGroup.com)<br><a href="https://fb.com/abhinavm17/">@theenigma017</a><br>-----<br><a href=\"/esportal/log\">View /log.txt</a></html><br>-<br><a href=\"/esportal/wipe\">Wipe /log.txt</a><br>-<br><a href=\"/esportal/format\">Format File System</a><br>-<br><a href=\"/firmware\">Upgrade ESPortal Firmware</a></html>");

                                                                                                                              ^

ESPortal:50:1: error: expected ';' before '}' token

 }

 ^

exit status 1

expected ')' before 'https'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by AbhinavM2000** [comment]
Probably missed a closing bracket somewhere, should be an easy fix.
